#!/bin/bash
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3
go test -run FailNoAgree
go test -run TestConcurrentStarts
go test -run TestRejoin
go test -run TestBackup
go test -run Persist1
go test -run Persist2
go test -run Persist3

